# Generated by Django 5.0.4 on 2024-05-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DONOR_DATA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=20)),
                ('d_email', models.EmailField(max_length=254)),
                ('d_mother', models.CharField(max_length=20)),
                ('d_father', models.CharField(max_length=20)),
                ('d_dob', models.IntegerField()),
                ('d_gender', models.CharField(max_length=20)),
                ('d_weight', models.IntegerField()),
                ('d_bloodgroup', models.CharField(max_length=20)),
                ('d_adhar', models.BigIntegerField(default=0)),
                ('d_uadhar', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
