# Generated by Django 5.0.4 on 2024-05-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_blooddonation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonation',
            name='blood_group',
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='blood_group_AB_negative',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='blood_group_AB_positive',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='blood_group_A_negative',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='blood_group_A_positive',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='blood_group_B_negative',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='blood_group_B_positive',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='blood_group_O_negative',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='blood_group_O_positive',
            field=models.IntegerField(default=0),
        ),
    ]
